### ISSUE TITLE
/battle: PVP 기본 기능 구현

### ISSUE THREAD

**Issue by dora-0** [Mikeds36/MPlugin#2]
### PVP 기본 기능 구현
- [x] /battle 명령어 추가
명령어 사용 시, 초기 설정 진행.
  - 3, 2, 1의 카운트다운 표시 (title)
  - 카운트다운을 표시할 때 효과음 재생 (note_block.pling)
  - 모든 유저를 특정 좌표로 이동 (-99, 34, -18)
  - 월드 경계를 60으로 설정 후, 100초 동안 1까지 줄임
  - 모든 보유 아이템 제거
  - 타이머 (bossbar)를 보이게 하기
  - 게임 모드를 어드벤쳐 모드로 전환
  - 밀치기 I이 인챈트된 막대기 지급
  - 재생 효과, 포화 효과 (Lv.127)를 2초 간 적용
  - BGM 재생 (music_disc.ward)

- [x] 전투 시작 시, 타이머가 작동하게 하기
  - 시간은 100초로 설정 (20틱 = 1초)
  - bossbar를 사용해 화면 위쪽에 남은 시간 게이지가 나타나도록 구현
  - bossbar의 제목이 남은 시간: %d 형태로 표시되게끔 하기

- [x] 전투 종료 시, 일괄적으로 실행할 작업 구현
  - 타이머 (bossbar) 숨기기 및 리셋
  - 월드 경계를 600000으로 설정
  - 모든 유저를 특정 좌표로 이동 (-90, 20, -45)
  - 게임 모드를 크리에이티브 모드로 전환

**Comment by MikedsKR** [comment]
- [x] 특정 아이템 사용시 효과 증정

- torch 사용시 전방 6블럭 앞에 크리퍼 생성 및 폭파

**Comment by dora-0** [comment]
작업 재시작 시 다시 오픈
